[versions]
agp = "8.13.0"
annotation = "1.9.1"
appcompatVersion = "1.7.1"
commonsCli = "1.10.0"
core = "1.17.0"
jacksonAnnotations = "2.20"
jacksonCore = "2.20.0"
jsonrpc4j = "1.5.0"
junit = "4.13.2"
junitJunit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
nanohttpd = "2.3.1"
okhttp = "5.2.1"
runner = "1.7.0"
uiautomator = "2.3.0"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
appcompat-v120 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commonsCli" }
core = { module = "androidx.core:core", version.ref = "core" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jacksonAnnotations" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jacksonCore" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonCore" }
jsonrpc4j = { module = "com.github.briandilley.jsonrpc4j:jsonrpc4j", version.ref = "jsonrpc4j" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v412 = { module = "junit:junit", version.ref = "junitJunit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
rules = { module = "androidx.test:rules", version.ref = "runner" }
runner = { module = "androidx.test:runner", version.ref = "runner" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

